### ISSUE TITLE
Any reason why lazy_static dev dep is 1.0.* instead of 1?

### ISSUE THREAD

**Issue by silwol** [tormol/encode_unicode#10]
The `lazy_static` crate is at version `1.4`, but the dev dependency of `encode_unicode` points to `1.0.*`. A quick check shows that the tests run with `1.4`. Is there any valid reason to keep it at `1.0` (effectively `1.0.2` atm, and possibly forever), or could it be updated?

**Comment by tormol** [comment]
Only for compatibility with old Rust versions.

(lazy_static 1.1 doesn't compile on Rust 1.15, and tests doesn't compile if dev-dependencies doesn't, even though lazy_static is only used in benchmarks which require nightly anyway.)

On master I've already relaxed it with commit 4ba893dd1c5c8708fbc36bcf99c9419732bbf211.

**Comment by silwol** [comment]
Ok, then we can close this bug, as it is fixed in master already. For the debian package we will probably patch the dev dependency for the tests to run properly, and remove it wit the update to the next release.
