### ISSUE TITLE
replace no_std feature with default std feature

### ISSUE THREAD

**Issue by cmr** [tormol/encode_unicode#3]
See eg https://github.com/tomprogrammer/rust-ascii/issues/29

**Comment by tormol** [comment]
Sorry for being so slow to respond.

I fixed this a while ago, but hadn't pushed anything.
Initially I was stuck on how to conditionally forward `std` to ascii, but then I realized nothing this crate use of ascii requires it, so `default-features=false` works out perfectly in this case.

With Rust 1.15 released weeks ago it's high time to make a release.
