### ISSUE TITLE
Implement Display for Utf16Char & Utf8Char

### ISSUE THREAD

**Issue by Susurrus** [tormol/encode_unicode#5]
Is there a reason this isn't implemented? Would be quite useful for me.

**Comment by Susurrus** [comment]
This applies to `Utf8Char` as well.

**Comment by tormol** [comment]
If I had a reason I've forgotten it.

**Comment by Susurrus** [comment]
So would you be against adding this?

**Comment by tormol** [comment]
Sorry for being so slow to reply,
No, I've released 0.3.1 with only this change.
