### ISSUE TITLE
Accepts certain overlong encodings

### ISSUE THREAD

**Issue by AljoschaMeyer** [tormol/encode_unicode#6]
`Utf8Char::from_slice_start` accepts [overlong encodings](https://en.wikipedia.org/wiki/UTF-8#Overlong_encodings):

```
Utf8Char::from_slice_start(&[[0xc1, 0x92]][..])
-> Ok('R', 2)
```

But the only valid utf-8 encoding for `'R'` is `[0x52]` (`[0b0101_0010]`).

encode_unicode version 0.3.2

*edit*: Judging from the comments on the [overlong check](0xc1, 0x92) (haven't fully grasped the code yet), you assume that overlong encodings have only zeros in the "content" bits of the first byte. But `[0xc1, 0x92]` (i.e. `[0b1100_0001 0b1001_0010]`) is overlong even though the first byte has a nonzero content bit.

**Comment by AljoschaMeyer** [comment]
I also wrote a fuzz test for [cargo-fuzz](https://fuzz.rs/book/cargo-fuzz.html) that checks whether `std::str::from_utf8` matches the behavior of `from_slice_start`, and the pull-requested code passed a few minutes of fuzzing (I'll just leave it running in the background for a few hours, and update here if it still finds bugs).

If you are open to including cargo-fuzz, I can do another pull request with the fuzz test case.

```rust
extern crate libfuzzer_sys;
extern crate encode_unicode;

use encode_unicode::Utf8Char;

fuzz_target!(|data: &[u8]| {
    if data.len() > 0 {
        // validate the result of encode_unicode against the std library
        match Utf8Char::from_slice_start(data) {
            Err(_) => assert!(std::str::from_utf8(data).is_err()),
            Ok((c, len)) => assert_eq!(c.as_str(), std::str::from_utf8(&data[..len]).unwrap()),
        }
    }
});
```

**Comment by tormol** [comment]
Good catch!

Fuzz tests would be nice, although for functions that take fixed-length inputs exhaustive checks are also an option as 2^32 values doesn't take that long to check.

My root logic error is that I forgot that going from one to two bytes only adds four content bits instead of five.
